"""
Lead scoring — rule-based rubric with Gemini for the reason sentence.
"""
from __future__ import annotations

import json
import os
import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.data.models import Lead

_SCORING_PROMPT_TEMPLATE = """You are scoring a real estate lead. Use this rubric exactly:
- HIGH: budget stated and realistic, timeline ready now or within ~30 days.
- MEDIUM: budget fits but timeline vague, or unclear budget but strong engagement.
- LOW: budget out of range, no clear timeline, low engagement.

Given:
Budget: {budget}
Preferences: {property_preferences}
Availability/timeline: {availability}

Return ONLY this JSON:
{{"score": "HIGH | MEDIUM | LOW", "reason": "<one sentence for salesperson>"}}"""


def _strip_fences(text: str) -> str:
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)
    return text.strip()


def _rule_based_score(lead: "Lead") -> str:
    """Fast heuristic pass — no LLM needed."""
    has_budget = bool(lead.budget)
    has_availability = bool(lead.availability)
    has_prefs = bool(lead.property_preferences)

    if has_budget and has_availability:
        return "HIGH"
    if has_budget or (has_prefs and has_availability):
        return "MEDIUM"
    return "LOW"


def _gemini_reason(lead: "Lead", score: str) -> str:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "GEMINI_API_KEY environment variable is not set."
        )
    import google.generativeai as genai  # type: ignore

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel("gemini-2.5-flash")

    prompt = _SCORING_PROMPT_TEMPLATE.format(
        budget=lead.budget or "unknown",
        property_preferences=lead.property_preferences or "unknown",
        availability=lead.availability or "unknown",
    )
    response = model.generate_content(prompt)
    raw = _strip_fences(response.text)
    data = json.loads(raw)
    return data.get("reason", f"Lead scored {score} based on available information.")


def score_lead(lead: "Lead") -> tuple[str, str]:
    """
    Return (score, reason_sentence).
    Score is determined by rule-based logic; reason is generated by Gemini.
    """
    score = _rule_based_score(lead)
    try:
        reason = _gemini_reason(lead, score)
    except Exception:
        reason = f"Lead scored {score} based on provided information."
    return score, reason
